searchguard:
  dynamic:
    http:
      xff:
        enabled: true
        remoteIpHeader: 'x-forwarded-for'
        trustedProxies: '.*'
        internalProxies: '.*'
    authc:
      openshift_domain:
        enabled: true
        order: 0
        http_authenticator:
          challenge: false
          type: io.fabric8.elasticsearch.plugin.auth.OpenShiftTokenAuthentication
        authentication_backend:
          type: io.fabric8.elasticsearch.plugin.auth.OpenShiftTokenAuthentication
          config:
             subjectAccessReviews:
               prometheus:
                 verb: get
                 resource: /metrics
               jaeger:
                 verb: get
                 resource: jaeger
                 namespace: set-in-run-script
                 resourceAPIGroup: elasticsearch.jaegertracing.io
               elasticsearch-operator:
                 verb: '*'
                 resource: '*'
                 namespace: '*'
                 resourceAPIGroup: logging.openshift.io
      authentication_domain_basic_internal:
        enabled: true
        order: 1
        http_authenticator:
          type: clientcert
          challenge: false
        authentication_backend:
          type: noop
