apiVersion: " operators.coreos.com/v1"
kind: "CatalogSourceConfig"
metadata:
  name: "cluster-logging"
  namespace: "openshift-marketplace"
spec:
  targetNamespace: "openshift-logging"
  packages: "cluster-logging"
